### ISSUE TITLE
glibc 2.32 and glibc 2.34 not found

### ISSUE THREAD

**Issue by khawar56** [MU-Data-Science/EVA#2]
OS versioning issue

**Comment by khawar56** [comment]
Solution: Update to Ubuntu 22.04.1 

Steps:
1 - SSH into the node 
2- Run Following 
```
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade
sudo do-release-upgrade
```

**Comment by raopr** [comment]
To run with Ubuntu 18.04, use freebayes 1.3.4. 

https://github.com/freebayes/freebayes/releases/download/v1.3.4/freebayes-1.3.4-linux-static-AMD64.gz

**Comment by raopr** [comment]
freebayes.tar has been updated with the above binary on Clemson and Wisconsin project directories.

**Comment by khawar56** [comment]
Acknowledge. ThanksOn Jan 31, 2023, at 6:11 AM, Praveen Rao ***@***.***> wrote:﻿
freebayes.tar has been updated with the above binary on Clemson and Wisconsin project directories.
